# Generated by Django 4.1.2 on 2022-10-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_rating_author_author_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='comment_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='post_rating',
        ),
    ]
